#!/usr/bin/env node

const path = require('path');
const { spawn } = require('child_process');
const { writeFile } = require('then-fs');

async function main() {
  const version = await bumpVersion();
  await run('git', ['add', '*']);
  await run('git', ['commit', '-am', '🚀 ' + version]);
  await run('git', ['push', 'origin', 'master']);
  await run('npm', ['publish', '--access=public']);
  console.log(`Rapid version ${version} published`);
}

async function bumpVersion() {
  const package = require('./package');
  const [major, minor, patch] = package.version.split(/\./g).map(n => +n);
  package.version = `${major}.${minor}.${patch + 1}`;
  await writeFile(path.join(__dirname, 'package.json'), JSON.stringify(package, null, 2));
  return package.version
}

function run(command, args, options) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, Object.assign({
      stdio: 'inherit'
    }, options));
    child.once('exit', resolve);
    child.once('error', reject);
  });
};

main().catch(error => console.log(error));
