#!/usr/bin/env node

const path = require('path');
const execa = require('execa');
const { writeFile } = require('then-fs');

async function main() {
  const version = await bumpVersion();
  await execa('git', ['add', '*']);
  await execa('git', ['commit', '-am', '🚀 ' + version]);
  await execa('git', ['push', 'origin', 'master']);
  await execa('npm', ['publish', '--access=public']);
  console.log(`Rapid version ${version} published`);
}

async function bumpVersion() {
  const package = require('./package');
  const [ major, minor, patch ] = package.version.split(/\./g).map(n => +n);
  package.version = `${major}.${minor}.${patch + 1}`;
  await writeFile(path.join(__dirname, 'package.json'), JSON.stringify(package, null, 2));
  return package.version
}

main().catch(error => console.log(error));
